---
title: "habitat_data_cleaning"
format: html
editor: visual
---

## Habitat data cleaning

##### Import

```{r}
library(tidyverse)
library(data.table)
habitat_data_raw <- read.csv("../data/distance_habitat_data.csv") 
habitat_data <- habitat_data_raw %>% 
  dplyr::select(-ID) %>%  
  drop_na()
```

##### Period metadata

```{r}
habitat_data <- habitat_data %>%   
  mutate(day = as.Date(date)) 
crops <- tibble(   
  crop = c("wheat", "sorghum", "bare soil", "chickpea"),   
  start_date = as.Date(c("2023-12-14", "2024-07-09", "2024-11-23", "2025-03-17")),   final_data   = as.Date(c("2024-07-08", "2024-11-22", "2025-03-16", "2025-07-15")))  

season <- c("spring", "summer", "autumn", "winter") 
years <- 2023:2025 
seasons <- bind_rows(lapply(years, function(an) {   
  tibble(
    season = season,     
         start_date = as.Date(paste0(an, c("-03-21", "-06-21", "-09-21", "-12-21"))),     final_data = as.Date(paste0(c(an, an, an, an + 1), c("-06-20", "-09-20", "-12-20", "-03-20")))) }))  

target_dates <- tibble(   
  period = 1:7,   
  start_date = as.Date(c("2024-03-20", "2024-05-25", "2024-07-15", "2024-09-19", "2024-12-10", "2025-02-15","2025-04-20")))  
days_crop <- crops %>%   
  rowwise() %>%   
  mutate(day = list(seq(start_date, final_data, by = "day"))) %>%   
  unnest(day) %>%   select(day, crop)  

habitat_data <- habitat_data %>%   
  left_join(days_crop, by = "day")  
season_days <- seasons %>%   
  rowwise() %>%   
  mutate(day = list(seq(start_date, final_data, by = "day"))) %>%   
  unnest(day) %>%   
  select(day, season)  
habitat_data <- habitat_data %>%   
  left_join(season_days, by = "day")  
period_days <- target_dates %>%   
  rowwise() %>%   
  mutate(day = list(seq(start_date, start_date + 6, by = "day"))) %>%   
  unnest(day) %>%   
  select(day, period)  
habitat_data <- habitat_data %>%   
  left_join(period_days, by = "day") 
```

##### Métadonnées position

```{r}
habitat_data <- habitat_data %>%   
  mutate(position = as.factor(substr(scanner, 4, 4)),     
         depth = as.factor(substr(scanner, 5, 6)),     
         orientation = as.factor(substr(scanner, 8, 8)))
```

##### Température et humidité

```{r}
probe_data_raw <- read.csv("../data/Diams_AF1W_soil.csv") 
probe_data <- probe_data_raw %>%
  mutate(date = as.POSIXct(date, format = "%Y-%m-%d %H:%M:%S"), 
         depth=as.factor(depth), 
         position=as.factor(position),
         hum = hum_soil, 
         temp = temp_soil) 


dt <- as.data.table(probe_data)
setorder(dt, depth, position, date)

dt[, temp_soil_amplitude := frollapply(temp_soil, 96, max, align = "right") -
                            frollapply(temp_soil, 96, min, align = "right"),
   by = .(depth, position)]

dt[, hum_soil_amplitude := frollapply(hum_soil, 96, max, align = "right") -
                           frollapply(hum_soil, 96, min, align = "right"),
   by = .(depth, position)]

probe_data_processed <- as.data.frame(dt)

habitat_data <- habitat_data %>%
  mutate(
    data_init = date,
    date = floor_date(ymd_hms(date), unit = "hour"),
    date = update(date, minute = 0, second = 0)
  ) %>%
  left_join(
    probe_data_processed %>% 
      drop_na() %>% mutate(depth = as.factor(depth)) %>%
      select(date, depth, position, hum, temp, temp_soil_amplitude, hum_soil_amplitude),
    by = c("date", "depth", "position"))
```

##### Densité racinaire

```{r}
dpi <- 1200 
pixels_per_cm <- dpi / 2.54 
root_density <- read.csv("../data/root_pixels_count.csv")  
root_density <- root_density %>%
  mutate(image_name = sub("\\.png$", "", root_density$file)) %>%  
  separate(file, into = c("bloc", "position", "orientation","year","month", "day", "hour", "minute", "fileextension1"), 
           sep = "_|\\.|H|M.| |-", remove = FALSE)%>%
  mutate(minute = if_else(minute == "01", "00", minute))%>%
  filter(hour %in% c("00", "06", "12", "18")) %>%
  mutate(date = ymd_hm(paste(year, month, day, hour, minute)))%>%
  mutate(scanner = as.factor(paste(position, orientation, sep = "_")))


root_density <- root_density %>%
  arrange(scanner, date) %>%  
  group_by(scanner) %>%
  mutate(lag_days = 9,
         date_target = date - days(9),
         date_target_24h = date - days(1)) %>%
  ungroup() %>%
  left_join(root_density %>% select(scanner, date, root_pixels_count) %>%
              rename(date_target = date,
                     root_pixels_count_lag = root_pixels_count),
            by = c("scanner", "date_target"), relationship = "many-to-many") %>%
  left_join(root_density %>% select(scanner, date, root_pixels_count) %>%
              rename(date_target_24h = date,
                     root_pixels_count_lag_6h = root_pixels_count),
            by = c("scanner", "date_target_24h"), relationship = "many-to-many") %>%
  mutate(root_growth_pixel_count = root_pixels_count - root_pixels_count_lag,
         root_mature_pixel_count = root_pixels_count - root_growth_pixel_count,
         root_growth_pixel_count_6h = root_pixels_count - root_pixels_count_lag_6h) %>%
  mutate(root_cm2_count = root_pixels_count / (pixels_per_cm^2),
         root_growth_cm2_count = root_growth_pixel_count / (pixels_per_cm^2),
         root_mature_cm2_count = root_mature_pixel_count / (pixels_per_cm^2),
         root_growth_cm2_count_24h = (root_growth_pixel_count_6h / (pixels_per_cm^2))/24)%>%
  mutate(root_growth_cm2_count_24h = case_when(
    root_growth_cm2_count_24h < 0 ~ 0,
    TRUE ~ root_growth_cm2_count_24h
  ))



habitat_data <- habitat_data %>%   
  left_join(root_density %>% select(image_name, root_cm2_count, root_growth_cm2_count, root_mature_cm2_count,root_growth_cm2_count_24h), by = "image_name")
```

```{r}
summary(habitat_data$root_cm2_count)   
habitat_data <- habitat_data %>%   
  mutate(root_density_level = case_when(
    root_cm2_count> quantile(root_cm2_count,0.75) ~ "high",                         
    root_cm2_count< quantile(root_cm2_count,0.25) ~ "low",   
    TRUE ~ "intermediate") )
```

##### Distance data transformation

In order to apply the log distribution to the "distances" variables, 0 must be eliminated, so a small offset is applied to all distance values.

```{r}
epsilon <- 1e-6 
habitat_data <- habitat_data %>%   
  mutate(distance_root_growth_obs = (distance_root_growth_obs/pixels_per_cm) + epsilon,         
         distance_root_mature_obs = (distance_root_mature_obs/pixels_per_cm) + epsilon,
         distance_root_growth_exp = (distance_root_growth_exp/pixels_per_cm) + epsilon,         
         distance_root_mature_exp = (distance_root_mature_exp/pixels_per_cm) + epsilon)
```

##### Cleaned data recording

```{r}
write.csv(habitat_data, "../data/distance_data_cleaned.csv", row.names = FALSE)
```
